logger:
  debug: true
  logLevel: DEBUG
  output:
    - stdout
    - ./examples/examples.log
parser:
  inputFile: examples/transactions-traderepublic.txt
  outputFile: examples/transactions-traderepublic.csv
  transaction:
    amount:
      symbol: "€"
      separator:
        thousand: ","
        decimal: "."





