logger:
  debug: true
  logLevel: DEBUG
  output:
    - stdout
    - ./examples/examples.log

facts:
    user: Hans Huber
    currency:
      symbol: €
      separator:
        thousand: ,
        decimal: .






